Fix textnode path
AngleSharp/AngleSharp.Diffing pull request #21
Opened 2022-02-23 20:44 UTC by edxlhornung

# Types of Changes

## Prerequisites

Please make sure you can check the following two boxes:

- [ x] I have read the **CONTRIBUTING** document
- [ x] My code follows the code style of this project

## Contribution Type

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue, please reference the issue id)
- [ x] New feature (non-breaking change which adds functionality, make sure to open an associated issue first)
- [ x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ x] I have added tests to cover my changes
- [ ] All new and existing tests passed

## Description

Please see #20 as it contains a good description of the problem and the implementation I did.

The issue was that the index of nodes without children (text and comment) present in the path property of diff nodes was incorrect. This is due to Core.ComparisonSource.GetPathIndex() returning the index inside the Children property (Which does not show nodes without children) instead of the ChildNodes property.

Thus I changed Core.ComparisonSource.GetPathIndex() to return the index inside ChildNodes. I also had to adjust the corresponding test cases in order to accommodate this new change.

2022-02-23 20:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AngleSharp/AngleSharp.Diffing?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AngleSharp/AngleSharp.Diffing?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AngleSharp/AngleSharp.Diffing?pullRequest=21) it.</sub>

2022-02-24 12:10 UTC, egil commented
@FlorianRappl seems like the build script needs a little TLC.

2022-03-04 14:19 UTC, egil commented
Im sorry for the lack of feedback on this. I will try to look at this during the weekend and get back to you @edxlhornung.

2022-03-04 14:32 UTC, FlorianRappl commented
Sorry missed out on it - currently quite a lot of things to do...

2022-03-04 19:56 UTC, edxlhornung commented
No worries! I also had a lot to do so I haven't continued my current projet with the library. I'll probably resume working on it on Monday.

2022-03-06 11:31 UTC, egil commented
Hi and sorry again, travel came in-between of this. Should have time in the beginning of the next week.

2022-03-14 12:11 UTC, egil commented
@FlorianRappl is the build error also an issue in the other AngleSharp repos? I dont have experience with Cake, but a quick google suggests this: https://github.com/cake-build/cake/issues/2262

2022-03-14 12:17 UTC, FlorianRappl commented
@egil just look at [AngleSharp.Core](https://github.com/AngleSharp/AngleSharp) and follow the steps there.

AFAIK right now the build is working. If `FileHelpers` is the issue you can have a look at e.g. [AngleSharp.Css](https://github.com/AngleSharp/AngleSharp.Css/blob/devel/tools/anglesharp.cake).

2022-03-14 12:32 UTC, egil commented
@edxlhornung I think you need to rebase your branch on `devel` and then the build pipeline should run. I managed to pin the cake addin package versions to something works, so if you do a rebase, we should be able to test your changes.

2022-03-15 10:07 UTC, egil requested changes
Thanks @edxlhornung. Your changes looks fine to me. My only concern is that I explicitly decided not to include leaf nodes originally, but I cannot remember why.

That said, it might just be affecting the diffing output and not diffing operations itself, so while this is a breaking change, its relatively benign, I think.

I am going to approve this, get it merged and push a preview release.

But before we do so, please update the changelog.md (rebase on devel first) with the changed line in the 0.18.0 section:

```text
- Changed <WRITE DESCRIPTION OF CHANGE HERE>. By [@edxlhornung](https://github.com/edxlhornung).
```

2022-03-17 09:18 UTC, egil approved these changes

2022-03-17 09:20 UTC, merged