update AngleSharp and AngleSharp.Css
AngleSharp/AngleSharp.Diffing pull request #38
Opened 2023-06-26 02:41 UTC by SimonCropp

so the nugets r all in sync

2023-06-26 02:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AngleSharp/AngleSharp.Diffing?pullRequest=38) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AngleSharp/AngleSharp.Diffing?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AngleSharp/AngleSharp.Diffing?pullRequest=38) it.</sub>

2023-06-27 17:00 UTC, egil commented
Yeah I've been waiting for the css package to move to V1. Looks like we're close.

2023-06-28 07:25 UTC, egil requested changes
No reason not to go to V1 here too

2023-06-28 07:25 UTC, egil commented on CHANGELOG.md
> +# 0.19.0
```suggestion
# 1.0.0
```

2023-06-29 10:24 UTC, egil commented
Hmm now that I think about it, I do not think we can push a none-preview version out which depends on preview packages? so perhaps lets version it as 1.0.0-preview until CSS package is v1. @FlorianRappl what do you think?

2023-06-29 10:43 UTC, FlorianRappl commented
Well we could do it (publish something that is based on a preview) but I fully agree that waiting for AngleSharp.Css 1.0.0 is the right move!

2024-10-14 00:19 UTC, egil commented
I keep running into issues with wanting to use AngleSharp v1 and not being able to, so pushed an updated that ignores the preview release of css. Diffing doesn't need all css features, in realilty just the parsing of `style` attributes content, so I feel ok with this.

2024-10-14 00:19 UTC, closed without merging